//
//  RDPRedirectionResultQueryResponse.h
//  ExampleRDP
//
//  Created by 霍驹 on 2018/3/6.
//  Copyright © 2018年 HJ. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RDPWsResponse.h"

@interface RDPRedirectionResultQueryResponse : RDPWsResponse

/**
 The merchant id that generated by RDP for merchant.
 */
@property(nonatomic, strong) NSString* mid;
/**
 Merchant’s order-id for the transaction as the identifier of the transaction.
 Recommended to be unique for each case of transaction.
 */
@property(nonatomic, strong) NSString* order_id;
/**
 The amount as is sent in the request
 */
@property(nonatomic, strong) NSString* transaction_id;
/**
 The datetime when the response is created
 */
@property(nonatomic, strong) NSString* created_timestamp;

/**
 Response code from acquirer. Format is specific to each Acquirer
 */
@property(nonatomic, strong) NSString* acquirer_response_code;

/**
 Description of the response code.
 */
@property(nonatomic, strong) NSString* acquirer_response_msg;
/**
 The response signature.
 */
@property(nonatomic, strong) NSString* signature;

/**
 The echo back of merchant_reference in the request
 */
@property(nonatomic, strong) NSString* merchant_reference;

/**
 
 The first 6 digits of card number
 */
@property(nonatomic, strong) NSString* first_6;

/**
 The last 4 digits of card number
 */
@property(nonatomic, strong) NSString* last_4;

/**
 The expiry date of the card used for transaction
 */
@property(nonatomic, strong) NSString* exp_date;

/**
 Merchant defined payer ID or customer ID. Used to identify a unique merchant's customer.
 */
@property(nonatomic, strong) NSString* payer_id;

/**
 The name of cardholder
 */
@property(nonatomic, strong) NSString* payer_name;

/**
 The email of customer or cardholder.
 */
@property(nonatomic, strong) NSString* payer_email;

/**
 The type of tokenization process. Possible values:
 C : Create   M : Modify   R : Remove
 */
@property(nonatomic, strong) NSString* transaction_type;

/**
 The token ID that represent OR replace the card data.
 */
@property(nonatomic, strong) NSString* token_id;




/**
 Method that called to parse response data from response RDP API
 @param data the object that will this method parse to parse and get that value
 */
- (void) parse :(NSData*)data;
@end
