//
//  RDPRedirectAPIResponse.h
//  RDPSDK
//
//  Created by Ferico Samuel on 5/29/17.
//  Copyright © 2017 d'Amigos. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RDPWsResponse.h"
/**
 Class to represent a response from Redirect API (DAPI)
 */
@interface RDPRedirectAPIResponse : RDPWsResponse
/**
 The merchant id that generated by RDP for merchant.
 */
@property(nonatomic, strong) NSString* mid;
/**
	The response signature.
 */
@property(nonatomic, strong) NSString* signature;
/**
	Indicates the time when the payment-page session is detroyed
*/
@property(nonatomic, strong) NSString* expired_timestamp;
/**
	The datetime when the response is created
*/
@property(nonatomic, strong) NSString* created_timestamp;
/**
	Merchant’s order-id for the transaction as the identifier of the transaction.
	Recommended to be unique for each case of transaction.
 */
@property(nonatomic, strong) NSString* order_id;
/**
	The amount as is sent in the request
*/
@property(nonatomic, strong) NSString* transaction_id;
/**
	The payment page URL where merchant's system need to redirect to
*/
@property(nonatomic, strong) NSString* payment_url;
/**
	 Method that called to parse response data from response RDP API
	 @param data the object that will this method parse to parse and get that value 
 */
- (void) parse :(NSData*)data;

@end
