//
//  RDPPaymentResultQueryResponse.h
//  ExampleRDP
//
//  Created by 霍驹 on 2018/3/7.
//  Copyright © 2018年 HJ. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RDPWsResponse.h"
@interface RDPPaymentResultQueryResponse : RDPWsResponse

/**
 The merchant id generated by RDP for merchant
 */
@property(nonatomic, strong) NSString* mid;

/**
 The merchant id generated by RDP for merchant, which is used when requesting the payment.
 */
@property(nonatomic, strong) NSString* request_mid;

/**
 An echo back to Merchant’s order-id for the transaction as the identifier of the transaction.
 */
@property(nonatomic, strong) NSString* order_id;

/**
 The RDP generated unique transaction- id, which is used heavily for identifying the resulted transaction in RDP system.
 */
@property(nonatomic, strong) NSString* transaction_id;

/**
 Echo back the amount as is sent in the request.
 */
@property(nonatomic, strong) NSString* request_amount;
@property(nonatomic, strong) NSString* request_ccy;
@property(nonatomic, strong) NSString* request_timestamp;
@property(nonatomic, strong) NSString* authorized_amount;
@property(nonatomic, strong) NSString* authorized_ccy;
@property(nonatomic, strong) NSString* transaction_type;
@property(nonatomic, strong) NSString* created_timestamp;
@property(nonatomic, strong) NSString* acquirer_response_code;
@property(nonatomic, strong) NSString* acquirer_response_msg;
@property(nonatomic, strong) NSString* signature;
@property(nonatomic, strong) NSString* acquirer_authorized_amount;
@property(nonatomic, strong) NSString* acquirer_authorized_ccy;
@property(nonatomic, strong) NSString* merchant_reference;
@property(nonatomic, strong) NSString* acquirer_created_timestamp;
@property(nonatomic, strong) NSString* acquirer_transaction_id;
@property(nonatomic, strong) NSString* acquirer_authorization_code;
@property(nonatomic, strong) NSString* first_6;
@property(nonatomic, strong) NSString* last_4;
@property(nonatomic, strong) NSString* exp_date;
@property(nonatomic, strong) NSString* payment_mode;
@property(nonatomic, strong) NSString* payer_id;
@property(nonatomic, strong) NSString* payer_name;
@property(nonatomic, strong) NSString* acquirer_mpi_eci;
@property(nonatomic, strong) NSString* uatp;
@property(nonatomic, strong) NSString* merchant_data1;
@end
