//
//  RDPRedirectAPIRedirectionResponse.h
//  RDPSDK
//
//  Created by Ferico Samuel on 5/29/17.
//  Copyright © 2017 d'Amigos. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RDPWsResponse.h"
#import "RDPRedirectAPIPaymentType.h"
/**
	Class to represent a response from Redirect API (RAPI) Redirection
*/
@interface RDPRedirectAPIRedirectionResponse : RDPWsResponse
/**
 	The merchant id that generated by RDP for merchant.
*/
@property(nonatomic, strong) NSString* mid;
/**
	The merchant id generated by RDP for merchant, which is used when requesting the payment
*/
@property(nonatomic, strong) NSString* request_mid;
/**
	Merchant’s order-id for the transaction as the identifier of the transaction.
	Recommended to be unique for each case of transaction.
*/
@property(nonatomic, strong) NSString* order_id;
/**
	The unique transaction-id generated by RDP
*/
@property(nonatomic, strong) NSString* transaction_id;
/**
	the amount as is sent in the request
*/
@property(nonatomic) float request_amount;
/**
	The currency as is sent in the request
*/
@property(nonatomic, strong) NSString* request_ccy;
/**
	The amount after applying all of others RDP features.
*/
@property(nonatomic) float authorized_amount;
/**
	The final currency that is going to be communicated to Bank/Acquirer.
*/
@property(nonatomic, strong) NSString* authorized_ccy;
/**
	The transaction type as is sent in the request in enum
*/
@property(nonatomic) enum RDPRedirectAPIPaymentType transaction_type;
/**
	The datetime when the response is created
*/
@property(nonatomic, strong) NSString* created_timestamp;
/**
	Response code from acquirer. Format is specific to each Acquirer
*/
@property(nonatomic, strong) NSString* acquirer_response_code;
/**
	Description of the response code
*/
@property(nonatomic, strong) NSString* acquirer_response_msg;
/**
	The response signature.
*/
@property(nonatomic, strong) NSString* signature;
/**
	The amount authorized by acquirer
*/
@property(nonatomic) float acquirer_authorized_amount;
/**
	The currency authorized by Acquirer.
*/
@property(nonatomic, strong) NSString* acquirer_authorized_ccy;
/**
	The merchant_reference in the request
*/
@property(nonatomic, strong) NSString* merchant_reference;
/**
	The datetime when the response is created. In a 24 hour format. Timezone vary depends on Acquirer
*/
@property(nonatomic, strong) NSString* acquirer_created_timestamp;
/**
	The transaction ID generated by Acquirer.
*/
@property(nonatomic, strong) NSString* acquirer_transaction_id;
/**
	The authorization code from the Bank. Only when it is available from the Bank response.
*/
@property(nonatomic, strong) NSString* acquirer_authorization_code;
/**
	The first 6 digits of card_no
 */
@property(nonatomic, strong) NSString* first_6;
/**
	The last 4 digits of card_no
 */
@property(nonatomic, strong) NSString* last_4;
/**
	The name of card-holder
 */
@property(nonatomic, strong) NSString* payer_name;
/**
	The expiry date of the card used for transaction
 */
@property(nonatomic, strong) NSString* exp_date;

@end
